version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@database.local:5432/bonusx_db
      - S3_ENDPOINT=http://storage.local:9000
      - S3_ACCESS_KEY_ID=NINJA_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=NINJA_SECRET_KEY
      - S3_BUCKET_NAME=bonusx-bucket
      - S3_REGION=us-east-1
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - PORT=80
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - postgres
      - minio
    networks:
      - bonusx-network

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bonusx_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bonusx-network

  minio:
    hostname: storage.local
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=NINJA_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=NINJA_SECRET_KEY
    volumes:
      - ./docker/storage_data:/data
    networks:
      - bonusx-network

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
