version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@database.local:5432/bonusx_db
      - S3_ENDPOINT=http://storage.local:9000
      - S3_ACCESS_KEY_ID=NINJA_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=NINJA_SECRET_KEY
      - S3_BUCKET_NAME=bonusx-bucket
      - S3_REGION=us-east-1
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-sk_test_development_key}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY:-pk_test_Y3JlYXRpdmUtY29sdC02MC5jbGVyay5hY2NvdW50cy5kZXYk}
      - CLERK_PEM_PUBLIC_KEY=${CLERK_PEM_PUBLIC_KEY:------BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA55zZWpy/h/6UjrPXq1bi\nZ31hSzw9vyOYuKTUmiqeYPNl/eimksFo0Jupo+rtllpH8+ax6rl6/mexTd9ohOZB\nmvz5eq0FCwRN/09WjqyEga3bDnu/2QlgM4lvIRXqoO6l67BRBwIXkamdhmfCc2yd\nob+XppGtf4suchoDZVpbqVp943liqlUGDlk8DLa976wZRhtjAes2HhH9li4PIUL7\nlJPOFdLu6nbDq7uT6cAPl1JGLOlD8VOsVnh+CEutmhW6HzxKHMB3ySDbsZlRcbuS\nt1VAtsjoxQI1TyiaHE1Add9rkxoVn7Cf5NVMxBs5k9IcwVwZ+AwSQeiS+0IVs3aU\n1wIDAQAB\n-----END PUBLIC KEY-----}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL:-https://creative-colt-60.clerk.accounts.dev/.well-known/jwks.json}
      - PORT=3000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - postgres
      - s3ninja
    networks:
      - bonusx-network
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bonusx_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bonusx-network

  s3ninja:
    hostname: storage.local
    image: scireum/s3-ninja:latest
    expose:
      - '9000'
    volumes:
      - ./docker/storage_data:/home/sirius/data
    networks:
      - bonusx-network

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
